Repository allanmozart/bookflix, pull requests merged in 2023-10, with the labels that each got.

#10 Auth Component created
  README.md
  src/components/Login/index.jsx
  src/components/RequireAuth/RequireAuth.jsx
  src/pages/catalogPage/index.jsx
  src/requests/auth/login.js
Labels: documentation, enhancement

#8 adding register page landing page
  public/assets/icons/key-6-16.png
  public/assets/icons/mail-16.png
  public/assets/icons/user-16.png
  public/assets/icons8-netflix-480.svg
  src/components/Icons/style.jsx
  src/components/Login/index.jsx
  src/components/Register/index.jsx
  src/components/Register/style.jsx
  src/components/logo/index.jsx
  src/pages/RegisterPage/index.jsx
  src/pages/RegisterPage/style.jsx
  src/pages/app/index.jsx
  src/requests/auth/register.js
Labels: enhancement

#11 Create Catalog component and add it to the catalogPage
  src/components/Catalog/index.jsx
  src/components/Catalog/style.jsx
  src/helpers/urls.js
  src/pages/catalogPage/index.jsx
  src/pages/catalogPage/style.jsx
  src/requests/auth/login.js
Labels: bug, enhancement, help wanted

#19 Logout - removing token and clearUserData
  README.md
  src/api/auth/login.js
  src/components/Login/index.jsx
  src/components/Login/style.jsx
  src/components/Logout/index.jsx
  src/components/Register/index.jsx
  src/components/UserContext/User.jsx
  src/components/buttons/style.jsx
  src/pages/MyBooksPage/index.jsx
  src/pages/RegisterPage/index.jsx
  src/pages/RegisterPage/style.jsx
  src/pages/catalogPage/index.jsx
Labels: bug

#20 12 poc catalog
  src/api/auth/login.js
  src/assets/errorBg.jpg
  src/assets/missingImage.png
  src/components/Catalog/index.jsx
  src/components/Catalog/style.jsx
  src/components/DefaultNavbar/index.jsx
  src/components/DefaultNavbar/style.jsx
  src/components/Loading/style.jsx
  src/components/Login/style.jsx
  src/components/Logout/index.jsx
  src/components/MyBookList/index.jsx
  src/components/MyBookList/style.jsx
  src/components/MyBooks/index.jsx
  src/components/MyBooks/style.jsx
  src/components/Register/style.jsx
  src/components/UserContext/User.jsx
  src/components/buttons/style.jsx
  src/global.css
  src/pages/Error/index.jsx
  src/pages/Error/style.js
  src/pages/LandingPage/index.jsx
  src/pages/LandingPage/style.jsx
  src/pages/MyBooksPage/index.jsx
  src/pages/MyBooksPage/style.jsx
  src/pages/NewBookPage/index.jsx
  src/pages/NewBookPage/style.jsx
  src/pages/app/index.jsx
  src/pages/catalogPage/index.jsx
  src/pages/catalogPage/style.jsx
  src/routes/Routes.jsx
  src/utils/firstName.js
Labels: bug, enhancement, help wanted
